### ISSUE TITLE
RC milestones

### ISSUE THREAD

**Issue by krispya** [pmndrs/directed#3]
This is a fluid list that anyone can edit.

- [ ] Documentation https://github.com/pmndrs/directed/pull/7
- [x] Class sugar layer https://github.com/pmndrs/directed
- [x] React bindings
- [x] Settle on recommended React usage https://github.com/pmndrs/directed/issues/1
- [ ] Settle on expected tag behavior https://github.com/pmndrs/directed/issues/2 https://github.com/pmndrs/directed/pull/5
